#include <samplerate.h>
#include <juce_audio_formats/juce_audio_formats.h>

#include <algorithm>
#include <array>
#include <cmath>
#include <cstdint>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <memory>
#include <numeric>
#include <stdexcept>
#include <vector>

namespace {
constexpr std::uint32_t kFormat=1, kPageFrames=256, kChannelsMax=2;
constexpr std::array<char,8> kMagic{'A','N','L','E','P','R','P','1'};
struct Key { std::uint64_t sourceId{},generation{},stream{},fingerprint{}; std::uint32_t sourceRate{},projectRate{},p{},q{},channels{},layout{}; };
struct Header { std::array<char,8> magic{kMagic}; std::uint32_t format{kFormat}; Key key{}; std::uint32_t pageFrames{kPageFrames}, totalFrames{}; };
struct PageRecord { std::uint32_t index{}, frames{}, checksum{}; };
void require(bool b,char const* m){if(!b)throw std::runtime_error(m);} std::uint32_t checksum(float const*x,size_t n){std::uint32_t h=2166136261u;auto p=reinterpret_cast<unsigned char const*>(x);for(size_t i=0;i<n*sizeof(float);++i)h=(h^p[i])*16777619u;return h;}
std::uint64_t fingerprint(Key const&k){std::uint64_t h=1469598103934665603ull;auto p=reinterpret_cast<unsigned char const*>(&k);for(size_t i=0;i<sizeof k;++i)h=(h^p[i])*1099511628211ull;return h;}
class Fixture {
 public: Fixture(int rate,int channels,std::filesystem::path file):file_(std::move(file)),rate_(rate),channels_(channels){juce::WavAudioFormat f;auto stream=juce::File(juce::String(file_.string())).createOutputStream();require(stream!=nullptr,"fixture stream");auto writer=std::unique_ptr<juce::AudioFormatWriter>(f.createWriterFor(stream.release(),rate,channels,16,{},0));require(writer!=nullptr,"fixture writer");juce::AudioBuffer<float>b(channels,4096);for(int start=0;start<16000;start+=4096){int n=std::min(4096,16000-start);for(int c=0;c<channels;++c)for(int i=0;i<n;++i)b.setSample(c,i,float(.25*std::sin((start+i)*(.011+c*.003))));require(writer->writeFromAudioSampleBuffer(b,0,n),"fixture write");}}~Fixture(){std::error_code e;std::filesystem::remove(file_,e);} std::filesystem::path const&path()const{return file_;}int rate()const{return rate_;}int channels()const{return channels_;} private:std::filesystem::path file_;int rate_,channels_;};
struct Converted { std::vector<float> pcm; std::uint32_t frames{}; };
Converted convert(std::filesystem::path const& path,int projectRate){juce::AudioFormatManager m;m.registerBasicFormats();auto reader=std::unique_ptr<juce::AudioFormatReader>(m.createReaderFor(juce::File(juce::String(path.string()))));require(reader&&reader->numChannels>0&&reader->numChannels<=kChannelsMax,"reader");const int channels=int(reader->numChannels);std::array<SRC_STATE*,kChannelsMax> states{};for(int c=0;c<channels;++c){int e{};states[c]=src_new(SRC_SINC_BEST_QUALITY,1,&e);require(states[c]&&e==0,"src new");}Converted result;std::array<std::array<float,1024>,kChannelsMax> input{},output{};std::array<float*,kChannelsMax> ptrs{};std::int64_t offset{};bool flush=false;while(!flush){int offered=offset<reader->lengthInSamples?int(std::min<std::int64_t>(1024,reader->lengthInSamples-offset)):0;for(int c=0;c<channels;++c)ptrs[c]=input[c].data();if(offered)require(reader->read(ptrs.data(),channels,offset,offered),"decoder read");std::array<long,kChannelsMax> got{};for(int c=0;c<channels;++c){SRC_DATA d{};d.data_in=offered?input[c].data():nullptr;d.input_frames=offered;d.data_out=output[c].data();d.output_frames=long(output[c].size());d.src_ratio=double(projectRate)/reader->sampleRate;d.end_of_input=offset+offered>=reader->lengthInSamples;require(src_process(states[c],&d)==0,"src worker");require(c==0||got[0]==d.output_frames_gen,"channel alignment");got[c]=d.output_frames_gen;}offset+=offered;for(long i=0;i<got[0];++i)for(int c=0;c<channels;++c)result.pcm.push_back(output[c][size_t(i)]);result.frames+=std::uint32_t(got[0]);flush=offset==reader->lengthInSamples&&got[0]==0;}for(int c=0;c<channels;++c)src_delete(states[c]);return result;}
void writeArtifact(std::filesystem::path const&path,Key key,Converted const& data){key.fingerprint=fingerprint(key);Header h{{kMagic},kFormat,key,kPageFrames,data.frames};auto temp=path;temp+=L".tmp";std::ofstream out(temp,std::ios::binary|std::ios::trunc);require(static_cast<bool>(out),"artifact open");out.write(reinterpret_cast<char const*>(&h),sizeof h);std::array<float,kPageFrames*kChannelsMax> page{};for(std::uint32_t p=0,at=0;at<data.frames;++p){auto n=std::min(kPageFrames,data.frames-at);std::fill(page.begin(),page.end(),0.0f);std::copy_n(data.pcm.data()+size_t(at)*key.channels,size_t(n)*key.channels,page.data());PageRecord r{p,n,checksum(page.data(),size_t(n)*key.channels)};out.write(reinterpret_cast<char const*>(&r),sizeof r);out.write(reinterpret_cast<char const*>(page.data()),std::streamsize(size_t(kPageFrames)*key.channels*sizeof(float)));at+=n;}out.close();require(static_cast<bool>(out),"artifact write");std::error_code e;std::filesystem::rename(temp,path,e);require(!e,"artifact publish");}
Converted openArtifact(std::filesystem::path const&path,Key key){key.fingerprint=fingerprint(key);std::ifstream in(path,std::ios::binary);require(static_cast<bool>(in),"artifact absent");Header h{};in.read(reinterpret_cast<char*>(&h),sizeof h);require(static_cast<bool>(in)&&h.magic==kMagic&&h.format==kFormat&&std::memcmp(&h.key,&key,sizeof key)==0&&h.pageFrames==kPageFrames,"artifact header");Converted d;d.frames=h.totalFrames;d.pcm.reserve(size_t(d.frames)*key.channels);std::array<float,kPageFrames*kChannelsMax> page{};for(std::uint32_t p=0,at=0;at<d.frames;++p){PageRecord r{};in.read(reinterpret_cast<char*>(&r),sizeof r);in.read(reinterpret_cast<char*>(page.data()),std::streamsize(size_t(kPageFrames)*key.channels*sizeof(float)));require(static_cast<bool>(in)&&r.index==p&&r.frames>0&&r.frames<=kPageFrames&&r.frames<=d.frames-at,"artifact record");require(checksum(page.data(),size_t(r.frames)*key.channels)==r.checksum,"artifact payload");d.pcm.insert(d.pcm.end(),page.begin(),page.begin()+size_t(r.frames)*key.channels);at+=r.frames;}return d;}
void fixture(int source,int project,int channels,std::filesystem::path const&root,int id){auto media=root/("fixture-"+std::to_string(id)+".wav");Fixture wav(source,channels,media);Key key{std::uint64_t(id),1,0,std::uint64_t{},std::uint32_t(source),std::uint32_t(project),std::uint32_t(project/std::gcd(source,project)),std::uint32_t(source/std::gcd(source,project)),std::uint32_t(channels),std::uint32_t(channels)};auto direct=convert(media,project);auto artifact=root/("prepared-"+std::to_string(id)+".anleprp");writeArtifact(artifact,key,direct);auto reopened=openArtifact(artifact,key);require(direct.pcm==reopened.pcm&&direct.frames==reopened.frames,"restart equal");double max{};for(size_t i=0;i<direct.pcm.size();++i)max=std::max(max,std::abs(double(direct.pcm[i]-reopened.pcm[i])));require(max<=2e-5,"real correctness");Key wrong=key;wrong.generation++;try{(void)openArtifact(artifact,wrong);throw std::runtime_error("stale accepted");}catch(std::runtime_error const&e){require(std::string(e.what())=="artifact header","wrong rejection");}auto bad=root/("bad-"+std::to_string(id)+".anleprp");{std::ofstream b(bad,std::ios::binary);b.write("bad",3);}try{(void)openArtifact(bad,key);throw std::runtime_error("corrupt accepted");}catch(std::runtime_error const&e){require(std::string(e.what())=="artifact header","corrupt rejection");}std::cout<<"prepared real source="<<source<<" project="<<project<<" channels="<<channels<<" frames="<<direct.frames<<" pages="<<(direct.frames+kPageFrames-1)/kPageFrames<<" reopen=equal max="<<max<<" cache-key=validated PASS\n";std::error_code ec;std::filesystem::remove(artifact,ec);std::filesystem::remove(bad,ec);}
}
int main(){try{auto root=std::filesystem::temp_directory_path()/"AudioNLE-prepared-real-media";std::filesystem::create_directories(root);fixture(44100,48000,1,root,1);fixture(48000,44100,2,root,2);fixture(44100,96000,2,root,3);fixture(96000,48000,2,root,4);std::error_code e;std::filesystem::remove(root,e);std::cout<<"prepared real-media WAV=PASS compressed-container=NoProductionDecoderBoundary persistent=atomic-temp-rename RAM=bounded-hot-pages-deferred\n";return 0;}catch(std::exception const&e){std::cerr<<"prepared real-media FAIL "<<e.what()<<'\n';return 1;}}
