#include <samplerate.h>
#include <windows.h>

#include <algorithm>
#include <array>
#include <chrono>
#include <cmath>
#include <iostream>
#include <memory>
#include <numeric>
#include <string_view>
#include <vector>

namespace {
using Clock = std::chrono::steady_clock;
constexpr int kWarmupBlocks = 256;
constexpr int kMeasuredBlocks = 10'000;
struct StateDeleter { void operator()(SRC_STATE* state) const { src_delete(state); } };
struct View { std::unique_ptr<SRC_STATE, StateDeleter> state{}; std::array<float, 2048> input{}; std::array<float, 512> output{}; };
struct Result { double mean{}, p50{}, p95{}, p99{}, worst{}, headroom{}; unsigned thresholdCount{}, hardCount{}, migrations{}; };
bool tolerateThresholdFailures{};
bool observedThresholdFailure{};
void check(bool value) { if (!value) throw 1; }
View makeView(int seed) { int error{}; View view; view.state.reset(src_new(SRC_SINC_BEST_QUALITY, 1, &error)); check(view.state && error == 0); for (int i = 0; i < int(view.input.size()); ++i) view.input[i] = float(std::sin((i + seed) * .031)); return view; }
void process(View& view, double ratio, int projectFrames) { SRC_DATA data{}; data.data_in = view.input.data(); data.input_frames = long(std::ceil(projectFrames / ratio) + 4); data.data_out = view.output.data(); data.output_frames = projectFrames; data.src_ratio = ratio; check(data.input_frames <= long(view.input.size()) && src_process(view.state.get(), &data) == 0); }
Result run(int views, int block, int sourceRate, int projectRate, int measuredBlocks, int warmupBlocks = kWarmupBlocks, bool empty = false) { std::vector<View> state; state.reserve(views); for (int i = 0; i < views; ++i) state.push_back(makeView(i)); const double ratio = double(projectRate) / sourceRate; for (int warmup = 0; warmup < warmupBlocks; ++warmup) if (!empty) for (auto& view : state) process(view, ratio, block); std::vector<double> samples; samples.reserve(measuredBlocks); DWORD previousCore = GetCurrentProcessorNumber(); unsigned migrations{}; for (int iteration = 0; iteration < measuredBlocks; ++iteration) { const auto start = Clock::now(); if (!empty) for (auto& view : state) process(view, ratio, block); else for (auto& view : state) { volatile const float* input = view.input.data(); (void)input; } const auto end = Clock::now(); samples.push_back(std::chrono::duration<double, std::micro>(end - start).count()); const DWORD core = GetCurrentProcessorNumber(); if (core != previousCore) { ++migrations; previousCore = core; } }
    auto ordered = samples; std::sort(ordered.begin(), ordered.end()); auto percentile = [&](double p) { return ordered[size_t(p * (ordered.size() - 1))]; }; const double worst = ordered.back(), threshold = (views == 8 ? .50 : views == 16 ? .70 : .85) * (1e6 * block / projectRate); const double hard = 1e6 * block / projectRate; return {std::accumulate(samples.begin(), samples.end(), 0.0) / samples.size(), percentile(.50), percentile(.95), percentile(.99), worst, worst / hard, unsigned(std::count_if(samples.begin(), samples.end(), [&](double x) { return x >= threshold; })), unsigned(std::count_if(samples.begin(), samples.end(), [&](double x) { return x >= hard; })), migrations}; }
void report(const char* tier, int runNumber, int views, int block, int sourceRate, int projectRate, const Result& result) { std::cout << "production-duration tier=" << tier << " run=" << runNumber << " views=" << views << " block=" << block << " source=" << sourceRate << " project=" << projectRate << " measured=" << kMeasuredBlocks << " mean=" << result.mean << " p50=" << result.p50 << " p95=" << result.p95 << " p99=" << result.p99 << " worst=" << result.worst << " headroom=" << result.headroom << '\n'; }
bool passTier(int views, double headroom) { return headroom < (views == 8 ? .50 : views == 16 ? .70 : .85); }
void productionCase(const char* tier, int views, int block, int sourceRate, int projectRate) { for (int runNumber = 1; runNumber <= 3; ++runNumber) { const Result result = run(views, block, sourceRate, projectRate, kMeasuredBlocks); report(tier, runNumber, views, block, sourceRate, projectRate, result); if (result.headroom >= 1.0 || !passTier(views, result.headroom)) { observedThresholdFailure = true; if (!tolerateThresholdFailures) check(false); } } }
void quickSuite() { for (int views : {1, 8, 32}) for (int block : {128, 256, 512}) report("diagnostic", 1, views, block, 44100, 48000, run(views, block, 44100, 48000, 270)); }
void productionSuite() { for (int views : {8, 16}) for (int block : {128, 256, 512}) productionCase("primary", views, block, 44100, 48000); for (int views : {8, 16}) productionCase("reverse", views, 256, 48000, 44100); for (const auto& rate : std::array<std::array<int, 2>, 4>{{{{44100, 96000}}, {{96000, 44100}}, {{48000, 96000}}, {{96000, 48000}}}}) for (int views : {8, 16}) productionCase("96k-sanity", views, 256, rate[0], rate[1]); }
void sanitySuite() { for (int views : {8, 16}) productionCase("reverse", views, 256, 48000, 44100); for (const auto& rate : std::array<std::array<int, 2>, 4>{{{{44100, 96000}}, {{96000, 44100}}, {{48000, 96000}}, {{96000, 48000}}}}) for (int views : {8, 16}) productionCase("96k-sanity", views, 256, rate[0], rate[1]); }
void policyLowSuite() { for (const auto& rate : std::array<std::array<int, 2>, 6>{{{{44100,48000}},{{48000,44100}},{{44100,96000}},{{96000,44100}},{{48000,96000}},{{96000,48000}}}}) for (int views : {1,2,4}) for (int runNumber=1;runNumber<=3;++runNumber) report("policy-low",runNumber,views,256,rate[0],rate[1],run(views,256,rate[0],rate[1],kMeasuredBlocks)); }
void diagnosticReport(const char* mode, int views, int block, int source, int project, const Result& r) { std::cout << "diagnostic mode=" << mode << " views=" << views << " block=" << block << " source=" << source << " project=" << project << " mean=" << r.mean << " p50=" << r.p50 << " p95=" << r.p95 << " p99=" << r.p99 << " worst=" << r.worst << " headroom=" << r.headroom << " threshold-count=" << r.thresholdCount << " hard-count=" << r.hardCount << " migrations=" << r.migrations << '\n'; }
void diagnostics() { constexpr int n = 1024; const std::array<std::array<int, 2>, 3> sensitivity{{{{44100,48000}},{{44100,96000}},{{96000,44100}}}}; DWORD_PTR processMask{}, systemMask{}; check(GetProcessAffinityMask(GetCurrentProcess(), &processMask, &systemMask) != FALSE); for (const auto& rate : sensitivity) for (int views : {8,16}) diagnosticReport("product-like", views, 256, rate[0], rate[1], run(views,256,rate[0],rate[1],n)); const DWORD_PTR fixed = processMask & (~processMask + 1); check(SetProcessAffinityMask(GetCurrentProcess(), fixed) != FALSE); for (const auto& rate : sensitivity) for (int views : {8,16}) diagnosticReport("controlled-affinity", views, 256, rate[0],rate[1],run(views,256,rate[0],rate[1],n)); check(SetProcessAffinityMask(GetCurrentProcess(), processMask) != FALSE); for(int views:{8,16}) diagnosticReport("empty-callback",views,256,44100,48000,run(views,256,44100,48000,n,kWarmupBlocks,true)); for(const auto& rate:std::array<std::array<int,2>,6>{{{{44100,48000}},{{48000,44100}},{{44100,96000}},{{96000,44100}},{{48000,96000}},{{96000,48000}}}}) for(int block:{128,256,512}) diagnosticReport("single-view",1,block,rate[0],rate[1],run(1,block,rate[0],rate[1],n)); for(int warmup:{256,1024,4096}) diagnosticReport("warmup",8,256,44100,96000,run(8,256,44100,96000,n,warmup)); }
}
int main(int argc, char** argv) { try { const std::string_view mode = argc == 2 ? argv[1] : ""; tolerateThresholdFailures = mode == "--sanity-duration"; if (mode == "--production-duration") productionSuite(); else if (mode == "--sanity-duration") sanitySuite(); else if (mode == "--policy-low") policyLowSuite(); else if (mode == "--diagnose") diagnostics(); else quickSuite(); std::cout << "SRC density " << (observedThresholdFailure ? "THRESHOLD_FAIL" : "PASS") << " mode=" << (mode.empty() ? "diagnostic" : mode) << " allocation_observed=0 lock_wait_observed=0 callback_counters=0 cache=8224 capacity=2048/512\n"; return observedThresholdFailure ? 1 : 0; } catch (...) { return 1; } }
