#include "source_runtime_engine.hpp"
#include <array>
#include <cmath>
#include <iostream>
#include <stdexcept>
using namespace audionle::source_runtime;
namespace { void need(bool v,const char*m){if(!v)throw std::runtime_error(m);} RuntimeIdentity id(std::uint64_t s,unsigned rate,Admission a){auto v=makeRuntimeIdentity(s,rate,a);v.channels=2;v.channelLayout=2;return v;} void run(){
 auto n=id(1,48000,Admission::NativeRate),r=id(2,44100,Admission::GuaranteedRealtime),p=id(3,48000,Admission::PreparedRequired);auto root=std::filesystem::temp_directory_path()/"AudioNLE-stereo";std::filesystem::create_directories(root);auto f=root/"stereo.anleprp";PreparedArtifactKey k{3,1,77,2,48000};writePreparedFixtureArtifact(f,k,20);auto ns=std::make_shared<SharedNativeSourceRuntime>(1,1,4096,2),rs=std::make_shared<SharedNativeSourceRuntime>(2,1,4096,2);SourceRuntime native(n,{},ns),realtime(r,{},rs),prepared(p,f);SourceNode nn(native),rn(realtime),pn(prepared);SharedSourceWorker w;w.add(native);w.add(realtime);w.add(prepared);ClipRuntimeView nv{0,0,512,n},rv{0,0,512,r},pv{0,0,512,p};std::array<float,512>a{},b{},c{},sum{};AudioBuffer ba{a.data(),256,2},bb{b.data(),256,2},bc{c.data(),256,2};need(nn.process(nv,0,ba)==SourceRenderResult::Ready,"stereo native");need(a[0]!=a[1],"native L/R");need(rn.process(rv,0,bb)==SourceRenderResult::Ready,"stereo realtime");need(pn.process(pv,0,bc)==SourceRenderResult::Unavailable,"stereo cold");w.drain();need(pn.process(pv,0,bc)==SourceRenderResult::Ready,"stereo prepared");need(c[0]!=c[1],"prepared L/R");for(unsigned i=0;i<sum.size();++i)sum[i]=a[i]+b[i]+c[i];need(sum[0]!=sum[1],"stereo sum preserves channels");AudioBuffer bad{a.data(),256,1};need(nn.process(nv,0,bad)==SourceRenderResult::Unsupported,"mismatch rejected");std::error_code e;std::filesystem::remove_all(root,e);std::cout<<"source runtime stereo mono/stereo native/realtime/prepared L/R=PASS native-bytes="<<ns->service().bytes()<<" stereo-bytes="<<ns->service().bytes()<<"\n";}}
int main(){try{run();return 0;}catch(std::exception const&e){std::cerr<<e.what()<<'\n';return 1;}}
