#include <windows.h>
#include <samplerate.h>

#include <array>
#include <cmath>
#include <cstdlib>
#include <cstring>
#include <iostream>
#include <optional>
#include <stdexcept>
#include <thread>
#include <type_traits>

#include "source_runtime_engine.hpp"

namespace {
using namespace audionle::source_runtime;
thread_local unsigned callbackDepth{};
thread_local unsigned hookDepth{};
struct Counters { unsigned mallocs{}, callocs{}, frees{}, heapAllocs{}, heapReAllocs{}, heapFrees{}, criticalSections{}, tryCriticalSections{}, srwExclusive{}, srwShared{}, trySrwExclusive{}, trySrwShared{}, waits{}, waitsEx{}, waitsMany{}, waitsManyEx{}, sleeps{}, sleepsEx{}, createFiles{}, readFiles{}, writeFiles{}; } counters{};
struct CallbackScope { CallbackScope(){++callbackDepth;} ~CallbackScope(){if(!callbackDepth)std::terminate();--callbackDepth;} };
void check(bool v,const char* m="check"){if(!v)throw std::runtime_error(m);}
struct ImportSlot { void** address{}; const char* importedFrom{}; };
ImportSlot findImport(const char* target){auto* b=reinterpret_cast<BYTE*>(GetModuleHandleW(nullptr));auto*d=reinterpret_cast<IMAGE_DOS_HEADER*>(b);check(d->e_magic==IMAGE_DOS_SIGNATURE,"DOS");auto*n=reinterpret_cast<IMAGE_NT_HEADERS64*>(b+d->e_lfanew);check(n->Signature==IMAGE_NT_SIGNATURE&&n->OptionalHeader.Magic==IMAGE_NT_OPTIONAL_HDR64_MAGIC,"PE");auto&r=n->OptionalHeader.DataDirectory[IMAGE_DIRECTORY_ENTRY_IMPORT];check(r.VirtualAddress,"imports");for(auto*x=reinterpret_cast<IMAGE_IMPORT_DESCRIPTOR*>(b+r.VirtualAddress);x->Name;++x){auto*names=reinterpret_cast<IMAGE_THUNK_DATA64*>(b+x->OriginalFirstThunk);auto*iat=reinterpret_cast<IMAGE_THUNK_DATA64*>(b+x->FirstThunk);if(!names)names=iat;for(;names->u1.AddressOfData;++names,++iat){if(names->u1.Ordinal&IMAGE_ORDINAL_FLAG64)continue;auto*name=reinterpret_cast<IMAGE_IMPORT_BY_NAME*>(b+names->u1.AddressOfData);if(!std::strcmp(reinterpret_cast<char*>(name->Name),target))return{reinterpret_cast<void**>(&iat->u1.Function),reinterpret_cast<char*>(b+x->Name)};}}throw std::runtime_error(target);}
std::optional<ImportSlot> optionalImport(const char* name){try{return findImport(name);}catch(const std::runtime_error&){return std::nullopt;}}
void patch(ImportSlot s,void* replacement,void*&original){DWORD old{};check(VirtualProtect(s.address,sizeof(void*),PAGE_READWRITE,&old),"VirtualProtect patch");original=*s.address;*s.address=replacement;DWORD ignored{};check(VirtualProtect(s.address,sizeof(void*),old,&ignored),"VirtualProtect protection");FlushInstructionCache(GetCurrentProcess(),s.address,sizeof(void*));}
void restore(ImportSlot s,void* original){DWORD old{};check(VirtualProtect(s.address,sizeof(void*),PAGE_READWRITE,&old),"VirtualProtect restore");*s.address=original;DWORD ignored{};check(VirtualProtect(s.address,sizeof(void*),old,&ignored),"VirtualProtect protection");FlushInstructionCache(GetCurrentProcess(),s.address,sizeof(void*));}

#define DEFINE_HOOK(name,type,member) type original##name{}; template<class...A> decltype(auto) invoke##name(A...a){return original##name(a...);} template<class...A> decltype(auto) hook##name(A...a){if(hookDepth!=0)return invoke##name(a...);++hookDepth;if(callbackDepth)++counters.member;if constexpr(std::is_void_v<decltype(invoke##name(a...))>){invoke##name(a...);--hookDepth;}else{auto result=invoke##name(a...);--hookDepth;return result;}}
using Malloc=void*(__cdecl*)(size_t); using Calloc=void*(__cdecl*)(size_t,size_t); using Free=void(__cdecl*)(void*); using HeapAllocFn=LPVOID(WINAPI*)(HANDLE,DWORD,SIZE_T); using HeapReAllocFn=LPVOID(WINAPI*)(HANDLE,DWORD,LPVOID,SIZE_T); using HeapFreeFn=BOOL(WINAPI*)(HANDLE,DWORD,LPVOID); using EnterCsFn=VOID(WINAPI*)(LPCRITICAL_SECTION); using TryEnterCsFn=BOOL(WINAPI*)(LPCRITICAL_SECTION); using AcquireSrwFn=VOID(WINAPI*)(PSRWLOCK); using TryAcquireSrwFn=BOOLEAN(WINAPI*)(PSRWLOCK); using WaitOneFn=DWORD(WINAPI*)(HANDLE,DWORD); using WaitOneExFn=DWORD(WINAPI*)(HANDLE,DWORD,BOOL); using WaitManyFn=DWORD(WINAPI*)(DWORD,const HANDLE*,BOOL,DWORD); using WaitManyExFn=DWORD(WINAPI*)(DWORD,const HANDLE*,BOOL,DWORD,BOOL); using SleepFn=VOID(WINAPI*)(DWORD); using SleepExFn=DWORD(WINAPI*)(DWORD,BOOL); using CreateFileWFn=HANDLE(WINAPI*)(LPCWSTR,DWORD,DWORD,LPSECURITY_ATTRIBUTES,DWORD,DWORD,HANDLE); using ReadFileFn=BOOL(WINAPI*)(HANDLE,LPVOID,DWORD,LPDWORD,LPOVERLAPPED); using WriteFileFn=BOOL(WINAPI*)(HANDLE,LPCVOID,DWORD,LPDWORD,LPOVERLAPPED);
DEFINE_HOOK(Malloc,Malloc,mallocs) DEFINE_HOOK(Calloc,Calloc,callocs) DEFINE_HOOK(Free,Free,frees) DEFINE_HOOK(HeapAlloc,HeapAllocFn,heapAllocs) DEFINE_HOOK(HeapReAlloc,HeapReAllocFn,heapReAllocs) DEFINE_HOOK(HeapFree,HeapFreeFn,heapFrees) DEFINE_HOOK(EnterCriticalSection,EnterCsFn,criticalSections) DEFINE_HOOK(TryEnterCriticalSection,TryEnterCsFn,tryCriticalSections) DEFINE_HOOK(AcquireSRWLockExclusive,AcquireSrwFn,srwExclusive) DEFINE_HOOK(AcquireSRWLockShared,AcquireSrwFn,srwShared) DEFINE_HOOK(TryAcquireSRWLockExclusive,TryAcquireSrwFn,trySrwExclusive) DEFINE_HOOK(TryAcquireSRWLockShared,TryAcquireSrwFn,trySrwShared) DEFINE_HOOK(WaitForSingleObject,WaitOneFn,waits) DEFINE_HOOK(WaitForSingleObjectEx,WaitOneExFn,waitsEx) DEFINE_HOOK(WaitForMultipleObjects,WaitManyFn,waitsMany) DEFINE_HOOK(WaitForMultipleObjectsEx,WaitManyExFn,waitsManyEx) DEFINE_HOOK(Sleep,SleepFn,sleeps) DEFINE_HOOK(SleepEx,SleepExFn,sleepsEx) DEFINE_HOOK(CreateFileW,CreateFileWFn,createFiles) DEFINE_HOOK(ReadFile,ReadFileFn,readFiles) DEFINE_HOOK(WriteFile,WriteFileFn,writeFiles)
#undef DEFINE_HOOK
struct Hook{const char*name;void*replacement;void**original;ImportSlot slot{};};
std::array<Hook,21> hooks{{{"malloc",reinterpret_cast<void*>(static_cast<Malloc>(hookMalloc)),reinterpret_cast<void**>(&originalMalloc)},{"calloc",reinterpret_cast<void*>(static_cast<Calloc>(hookCalloc)),reinterpret_cast<void**>(&originalCalloc)},{"free",reinterpret_cast<void*>(static_cast<Free>(hookFree)),reinterpret_cast<void**>(&originalFree)},{"HeapAlloc",reinterpret_cast<void*>(static_cast<HeapAllocFn>(hookHeapAlloc)),reinterpret_cast<void**>(&originalHeapAlloc)},{"HeapReAlloc",reinterpret_cast<void*>(static_cast<HeapReAllocFn>(hookHeapReAlloc)),reinterpret_cast<void**>(&originalHeapReAlloc)},{"HeapFree",reinterpret_cast<void*>(static_cast<HeapFreeFn>(hookHeapFree)),reinterpret_cast<void**>(&originalHeapFree)},{"EnterCriticalSection",reinterpret_cast<void*>(static_cast<EnterCsFn>(hookEnterCriticalSection)),reinterpret_cast<void**>(&originalEnterCriticalSection)},{"TryEnterCriticalSection",reinterpret_cast<void*>(static_cast<TryEnterCsFn>(hookTryEnterCriticalSection)),reinterpret_cast<void**>(&originalTryEnterCriticalSection)},{"AcquireSRWLockExclusive",reinterpret_cast<void*>(static_cast<AcquireSrwFn>(hookAcquireSRWLockExclusive)),reinterpret_cast<void**>(&originalAcquireSRWLockExclusive)},{"AcquireSRWLockShared",reinterpret_cast<void*>(static_cast<AcquireSrwFn>(hookAcquireSRWLockShared)),reinterpret_cast<void**>(&originalAcquireSRWLockShared)},{"TryAcquireSRWLockExclusive",reinterpret_cast<void*>(static_cast<TryAcquireSrwFn>(hookTryAcquireSRWLockExclusive)),reinterpret_cast<void**>(&originalTryAcquireSRWLockExclusive)},{"TryAcquireSRWLockShared",reinterpret_cast<void*>(static_cast<TryAcquireSrwFn>(hookTryAcquireSRWLockShared)),reinterpret_cast<void**>(&originalTryAcquireSRWLockShared)},{"WaitForSingleObject",reinterpret_cast<void*>(static_cast<WaitOneFn>(hookWaitForSingleObject)),reinterpret_cast<void**>(&originalWaitForSingleObject)},{"WaitForSingleObjectEx",reinterpret_cast<void*>(static_cast<WaitOneExFn>(hookWaitForSingleObjectEx)),reinterpret_cast<void**>(&originalWaitForSingleObjectEx)},{"WaitForMultipleObjects",reinterpret_cast<void*>(static_cast<WaitManyFn>(hookWaitForMultipleObjects)),reinterpret_cast<void**>(&originalWaitForMultipleObjects)},{"WaitForMultipleObjectsEx",reinterpret_cast<void*>(static_cast<WaitManyExFn>(hookWaitForMultipleObjectsEx)),reinterpret_cast<void**>(&originalWaitForMultipleObjectsEx)},{"Sleep",reinterpret_cast<void*>(static_cast<SleepFn>(hookSleep)),reinterpret_cast<void**>(&originalSleep)},{"SleepEx",reinterpret_cast<void*>(static_cast<SleepExFn>(hookSleepEx)),reinterpret_cast<void**>(&originalSleepEx)},{"CreateFileW",reinterpret_cast<void*>(static_cast<CreateFileWFn>(hookCreateFileW)),reinterpret_cast<void**>(&originalCreateFileW)},{"ReadFile",reinterpret_cast<void*>(static_cast<ReadFileFn>(hookReadFile)),reinterpret_cast<void**>(&originalReadFile)},{"WriteFile",reinterpret_cast<void*>(static_cast<WriteFileFn>(hookWriteFile)),reinterpret_cast<void**>(&originalWriteFile)}}};
void installAll(){for(auto&h:hooks){h.slot=findImport(h.name);void*o{};patch(h.slot,h.replacement,o);*h.original=o;}} void restoreAll(){for(auto&h:hooks)restore(h.slot,*h.original);} bool zero(){Counters empty{};return std::memcmp(&counters,&empty,sizeof counters)==0;}
void positive(){HANDLE heap=GetProcessHeap(),event=CreateEventW(nullptr,TRUE,TRUE,nullptr);check(event,"event");CRITICAL_SECTION cs{};SRWLOCK srw=SRWLOCK_INIT;const wchar_t path[]=L"AudioNLE_iat_harness.tmp";{CallbackScope s;void*p=std::malloc(8),*q=std::calloc(2,4);std::free(p);std::free(q);void*hp=HeapAlloc(heap,0,8);hp=HeapReAlloc(heap,0,hp,16);check(HeapFree(heap,0,hp),"heap");InitializeCriticalSection(&cs);EnterCriticalSection(&cs);LeaveCriticalSection(&cs);check(TryEnterCriticalSection(&cs),"try cs");LeaveCriticalSection(&cs);DeleteCriticalSection(&cs);AcquireSRWLockExclusive(&srw);ReleaseSRWLockExclusive(&srw);AcquireSRWLockShared(&srw);ReleaseSRWLockShared(&srw);check(TryAcquireSRWLockExclusive(&srw),"try exclusive");ReleaseSRWLockExclusive(&srw);check(TryAcquireSRWLockShared(&srw),"try shared");ReleaseSRWLockShared(&srw);check(WaitForSingleObject(event,0)==WAIT_OBJECT_0,"wait");check(WaitForSingleObjectEx(event,0,FALSE)==WAIT_OBJECT_0,"waitex");HANDLE es[]={event};check(WaitForMultipleObjects(1,es,FALSE,0)==WAIT_OBJECT_0,"waitmany");check(WaitForMultipleObjectsEx(1,es,FALSE,0,FALSE)==WAIT_OBJECT_0,"waitmanyex");Sleep(0);check(SleepEx(0,FALSE)==0,"sleepex");HANDLE f=CreateFileW(path,GENERIC_READ|GENERIC_WRITE,0,nullptr,CREATE_ALWAYS,FILE_ATTRIBUTE_TEMPORARY,nullptr);check(f!=INVALID_HANDLE_VALUE,"file");char w[]="rt",r[2]{};DWORD n{};check(WriteFile(f,w,2,&n,nullptr)&&n==2,"write");SetFilePointer(f,0,nullptr,FILE_BEGIN);check(ReadFile(f,r,2,&n,nullptr)&&n==2&&!std::memcmp(w,r,2),"read");CloseHandle(f);}DeleteFileW(path);CloseHandle(event);check(counters.mallocs&&counters.callocs&&counters.frees,"CRT positive");check(counters.heapAllocs&&counters.heapReAllocs&&counters.heapFrees,"heap positive");check(counters.criticalSections&&counters.tryCriticalSections&&counters.srwExclusive&&counters.srwShared&&counters.trySrwExclusive&&counters.trySrwShared,"lock positive");check(counters.waits&&counters.waitsEx&&counters.waitsMany&&counters.waitsManyEx&&counters.sleeps&&counters.sleepsEx,"wait positive");check(counters.createFiles&&counters.readFiles&&counters.writeFiles,"file positive");}
void negative(){counters={};{CallbackScope s;int sum{};std::array<char,64>a{},b{};for(int i=0;i<512;++i){sum+=i;a[size_t(i)%a.size()]=char(sum);}std::memcpy(b.data(),a.data(),a.size());check(sum&&a[0]==b[0]);}check(zero(),"negative observed event");}
void crossThread(){counters={};std::thread t([]{void*p=std::malloc(8);std::free(p);HANDLE h=GetProcessHeap();void*q=HeapAlloc(h,0,8);HeapFree(h,0,q);CRITICAL_SECTION cs{};InitializeCriticalSection(&cs);EnterCriticalSection(&cs);LeaveCriticalSection(&cs);DeleteCriticalSection(&cs);HANDLE e=CreateEventW(nullptr,TRUE,TRUE,nullptr);WaitForSingleObject(e,0);CloseHandle(e);const wchar_t path[]=L"AudioNLE_iat_worker.tmp";HANDLE f=CreateFileW(path,GENERIC_READ|GENERIC_WRITE,0,nullptr,CREATE_ALWAYS,FILE_ATTRIBUTE_TEMPORARY,nullptr);if(f!=INVALID_HANDLE_VALUE){char x=1;DWORD n{};WriteFile(f,&x,1,&n,nullptr);CloseHandle(f);DeleteFileW(path);}});t.join();check(zero(),"cross-thread leakage");}
void process(SRC_STATE*s,std::array<float,2048>&in,std::array<float,512>&out){SRC_DATA d{};d.data_in=in.data();d.input_frames=512;d.data_out=out.data();d.output_frames=long(out.size());d.src_ratio=48000.0/44100.0;check(src_process(s,&d)==0&&d.output_frames_gen>0,"src_process");}
void smoke(){int e{};SRC_STATE*s=src_new(SRC_SINC_BEST_QUALITY,1,&e);check(s&&e==0,"src_new");std::array<float,2048>in{};std::array<float,512>out{};for(size_t i=0;i<in.size();++i)in[i]=std::sin(float(i)*.031f);counters={};{CallbackScope c;process(s,in,out);}check(zero(),"src first-use event");{CallbackScope c;process(s,in,out);}check(zero(),"src steady-state event");src_delete(s);}
void preparedSmoke(){std::array<float,512> prepared{};std::array<float,512> output{};for(size_t i=0;i<prepared.size();++i)prepared[i]=std::sin(float(i)*.017f);unsigned srcProcessCalls{};counters={};{CallbackScope c;for(size_t i=0;i<output.size();++i)output[i]=prepared[i];}check(zero(),"prepared playback event");check(srcProcessCalls==0&&output==prepared,"prepared callback contract");}
void preparedArtifactResidency(){
  const auto root=std::filesystem::temp_directory_path()/"AudioNLE-iat-prepared-artifact";
  std::filesystem::create_directories(root); const auto path=root/"stereo.anleprp";
  PreparedArtifactKey key{71,3,17,2,48000}; writePreparedFixtureArtifact(path,key,24); auto runtime=makePreparedResidency(path,key);
  std::array<float,512> output{};
  // A cold miss includes the real fixed-table demand publication, but no I/O.
  constexpr unsigned pageFrames=256; counters={}; bool ready{}; {CallbackScope c;ready=preparedCallback(*runtime,5*pageFrames,pageFrames,output.data());}
  check(!ready&&std::all_of(output.begin(),output.end(),[](float x){return x==0.0f;}),"prepared artifact cold"); check(zero(),"prepared artifact cold event");
  drainPrepared(*runtime); counters={}; {CallbackScope c;ready=preparedCallback(*runtime,5*pageFrames,pageFrames,output.data());}
  check(ready&&zero(),"prepared artifact reload event");
  // Load page zero and its demand-triggered prefetch page one off callback.
  output.fill(0); preparedCallback(*runtime,0,pageFrames,output.data()); drainPrepared(*runtime); counters={}; {CallbackScope c;ready=preparedCallback(*runtime,250,12,output.data());}
  check(ready&&zero(),"prepared artifact stereo seam event");
  // File I/O on the worker while a resident callback runs is excluded by the
  // existing thread-local callback marker/cross-thread attribution control.
  preparedCallback(*runtime,8*pageFrames,pageFrames,output.data()); std::thread worker([&]{servicePrepared(*runtime);}); counters={}; {CallbackScope c;ready=preparedCallback(*runtime,0,16,output.data());} worker.join(); check(ready&&zero(),"prepared artifact worker attribution");
  // Force eviction/reload; every callback portion remains inside the IAT scope.
  for(unsigned p=2;p<22;++p){counters={}; {CallbackScope c;ready=preparedCallback(*runtime,p*pageFrames,1,output.data());} check(zero(),"prepared artifact eviction callback event"); if(!ready)drainPrepared(*runtime);}
  counters={}; {CallbackScope c;ready=preparedCallback(*runtime,0,pageFrames,output.data());} check(!ready&&zero(),"prepared artifact evicted cold event"); drainPrepared(*runtime); counters={}; {CallbackScope c;ready=preparedCallback(*runtime,0,pageFrames,output.data());} check(ready&&zero(),"prepared artifact evicted reload event"); std::error_code ec;std::filesystem::remove_all(root,ec);
}
void sourceRuntimeIat(){
  const auto root=std::filesystem::temp_directory_path()/"AudioNLE-iat-source-runtime";std::filesystem::create_directories(root);const auto file=root/"prepared.anleprp";PreparedArtifactKey key{3,1,77,1,48000};writePreparedFixtureArtifact(file,key,20);
  auto ni=makeRuntimeIdentity(1,48000,Admission::NativeRate),ri=makeRuntimeIdentity(2,44100,Admission::GuaranteedRealtime),pi=makeRuntimeIdentity(3,48000,Admission::PreparedRequired);SourceRuntime native(ni),realtime(ri),prepared(pi,file);SharedSourceWorker worker;worker.add(native);worker.add(realtime);worker.add(prepared);ClipRuntimeView nv{0,0,512,ni},rv{0,0,512,ri},pv{0,0,512,pi};SourceNode n(native),r(realtime),p(prepared);std::array<float,256>a{},b{},c{};SourceRenderResult result{};
  counters={};{CallbackScope scope;result=n.process(nv,0,256,a.data());}check(result==SourceRenderResult::Ready&&zero()&&native.realtimeCalls()==0&&native.preparedCalls()==0,"runtime native IAT");
  counters={};{CallbackScope scope;result=r.process(rv,0,256,b.data());}check(result==SourceRenderResult::Ready&&zero()&&realtime.realtimeCalls()>0,"runtime realtime IAT");
  counters={};{CallbackScope scope;result=p.process(pv,0,256,c.data());}check(result==SourceRenderResult::Unavailable&&std::all_of(c.begin(),c.end(),[](float x){return x==0;})&&zero(),"runtime prepared cold IAT");worker.drain();
  counters={};{CallbackScope scope;result=p.process(pv,0,256,c.data());}check(result==SourceRenderResult::Ready&&zero()&&prepared.realtimeCalls()==0,"runtime prepared reload IAT");
  counters={};{CallbackScope scope;result=n.process(nv,0,64,a.data());check(result==SourceRenderResult::Ready,"mixed native");result=r.process(rv,0,64,b.data());check(result==SourceRenderResult::Ready,"mixed realtime");result=p.process(pv,0,64,c.data());check(result==SourceRenderResult::Ready,"mixed prepared");}check(zero()&&native.realtimeCalls()==0&&prepared.realtimeCalls()==0&&realtime.realtimeCalls()>0,"runtime mixed IAT");
  ClipRuntimeView stale=nv;stale.identity.generation=2;counters={};{CallbackScope scope;result=n.process(stale,0,64,a.data());}check(result==SourceRenderResult::Stale&&zero(),"runtime stale IAT");
  ClipRuntimeView nativeMiss=nv;nativeMiss.sourceStart=2048;counters={};{CallbackScope scope;result=n.process(nativeMiss,0,64,a.data());}check(result==SourceRenderResult::Unavailable&&zero(),"runtime native miss IAT");worker.drain();counters={};{CallbackScope scope;result=n.process(nativeMiss,0,64,a.data());}check(result==SourceRenderResult::Ready&&zero(),"runtime native refill IAT");
  for(unsigned page=2;page<12;++page){ClipRuntimeView saturated=pv;saturated.sourceStart=std::int64_t(page)*256;counters={};{CallbackScope scope;result=p.process(saturated,0,1,c.data());}check(result==SourceRenderResult::Unavailable&&zero(),"runtime queue saturation IAT");}worker.drain();
  std::thread concurrent([&]{worker.drain();});counters={};{CallbackScope scope;result=p.process(pv,0,16,c.data());}concurrent.join();check((result==SourceRenderResult::Ready||result==SourceRenderResult::Unavailable)&&zero(),"runtime worker concurrency IAT");
  std::error_code ec;std::filesystem::remove_all(root,ec);
}
}
int main(){try{installAll();counters={};positive();negative();crossThread();smoke();preparedSmoke();preparedArtifactResidency();sourceRuntimeIat();restoreAll();counters={};{CallbackScope s;void*p=std::malloc(8);std::free(p);}check(zero(),"restore");installAll();restoreAll();std::cout<<"IAT Windows RT PASS routes";for(const auto&h:hooks)std::cout<<' '<<h.name<<'='<<h.slot.importedFrom;std::cout<<" controls=positive,negative,cross-thread runtime=native,realtime,prepared-cold-reload,mixed\n";for(const auto&route:std::array<std::array<const char*,2>,7>{{{{"realloc","realloc"}},{{"aligned_allocation","_aligned_malloc"}},{{"aligned_free","_aligned_free"}},{{"operator_new","??2@YAPEAX_K@Z"}},{{"operator_delete","??3@YAXPEAX@Z"}},{{"operator_new_array","??_U@YAPEAX_K@Z"}},{{"operator_delete_array","??_V@YAXPEAX@Z"}}}})std::cout<<"allocator-route "<<route[0]<<'='<<(optionalImport(route[1])?"MaterialBlindSpot":"NotPresentInRelevantTargetPath")<<'\n';return 0;}catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 1;}}
